"use client";

import { useState, useEffect } from "react";
import { ArrowLeft, Smartphone, CheckCircle, QrCode, Loader2 } from "lucide-react";
import Link from "next/link";

interface BinancePaymentProps {
    productInfo: {
        id: number;
        title: string;
        price: string;
        seller: string;
    };
    onBack: () => void;
    onSuccess: () => void;
}

type PaymentStatus = "pending" | "waiting" | "success";

export function BinancePayment({ productInfo, onBack, onSuccess }: BinancePaymentProps) {
    const [paymentStatus, setPaymentStatus] = useState<PaymentStatus>("pending");
    const [countdown, setCountdown] = useState(5);
    const [orderId] = useState(`BP-${Date.now()}`);

    // Mock QR Code URL (in production, this would be generated by Binance Pay API)
    const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(`binance://pay/${orderId}`)}`;

    useEffect(() => {
        if (paymentStatus === "waiting") {
            // Simulate payment confirmation after 5 seconds
            const timer = setInterval(() => {
                setCountdown((prev) => {
                    if (prev <= 1) {
                        clearInterval(timer);
                        setPaymentStatus("success");
                        return 0;
                    }
                    return prev - 1;
                });
            }, 1000);

            return () => clearInterval(timer);
        }
    }, [paymentStatus]);

    const handleGenerateQR = () => {
        setPaymentStatus("waiting");
    };

    if (paymentStatus === "success") {
        return (
            <div className="space-y-6 text-center py-12">
                <div className="w-20 h-20 rounded-full bg-green-500/20 flex items-center justify-center mx-auto">
                    <CheckCircle className="text-green-500" size={40} />
                </div>
                <div>
                    <h3 className="text-2xl font-bold text-foreground mb-2">Payment Successful!</h3>
                    <p className="text-muted-foreground">
                        Your payment has been received and processed.
                    </p>
                </div>

                <div className="bg-secondary/30 p-4 rounded-xl">
                    <div className="text-xs text-muted-foreground mb-1">Order ID</div>
                    <div className="font-mono text-sm text-foreground">{orderId}</div>
                </div>

                <div className="p-4 bg-yellow-500/10 border border-yellow-500/20 rounded-xl text-sm">
                    <div className="font-semibold text-foreground mb-2">⚡ Instant Transfer</div>
                    <p className="text-muted-foreground text-xs">
                        Funds will be automatically transferred to the seller's Binance UID upon delivery confirmation.
                    </p>
                </div>

                <div className="space-y-3">
                    <Link
                        href="/account/orders"
                        className="block px-6 py-3 rounded-full bg-primary text-primary-foreground font-semibold hover:opacity-90 transition-opacity"
                    >
                        View My Orders
                    </Link>
                    <button
                        onClick={onSuccess}
                        className="block w-full px-6 py-3 rounded-full bg-secondary text-secondary-foreground font-semibold hover:bg-secondary/80 transition-colors"
                    >
                        Close
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <button
                onClick={onBack}
                className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
            >
                <ArrowLeft size={18} />
                <span>Back to payment options</span>
            </button>

            {paymentStatus === "pending" && (
                <div className="space-y-6">
                    {/* Binance Pay Logo/Banner */}
                    <div className="text-center p-8 bg-gradient-to-br from-yellow-500/10 to-yellow-600/20 rounded-2xl border border-yellow-500/20">
                        <div className="text-6xl mb-4">💰</div>
                        <h3 className="text-2xl font-bold text-foreground mb-2">Binance Pay</h3>
                        <p className="text-muted-foreground">Fast, secure, and 0 fees</p>
                    </div>

                    {/* Payment Details */}
                    <div className="space-y-3">
                        <div className="flex justify-between p-4 bg-secondary/30 rounded-xl">
                            <span className="text-muted-foreground">Amount</span>
                            <span className="font-bold text-foreground">{productInfo.price} USDT</span>
                        </div>
                        <div className="flex justify-between p-4 bg-secondary/30 rounded-xl">
                            <span className="text-muted-foreground">Transaction Fee</span>
                            <span className="font-bold text-green-500">FREE</span>
                        </div>
                        <div className="flex justify-between p-4 bg-yellow-500/10 border border-yellow-500/20 rounded-xl">
                            <span className="font-semibold text-foreground">Total</span>
                            <span className="font-bold text-yellow-500 text-lg">{productInfo.price} USDT</span>
                        </div>
                    </div>

                    {/* Info */}
                    <div className="p-4 bg-blue-500/10 border border-blue-500/20 rounded-xl text-sm">
                        <div className="font-semibold text-foreground mb-2">📱 How to Pay</div>
                        <ol className="text-muted-foreground space-y-2 text-xs list-decimal list-inside">
                            <li>Click "Generate QR Code" below</li>
                            <li>Open Binance app on your phone</li>
                            <li>Scan the QR code or tap to auto-open</li>
                            <li>Confirm payment in Binance app</li>
                        </ol>
                    </div>

                    {/* Generate Button */}
                    <button
                        onClick={handleGenerateQR}
                        className="w-full px-6 py-4 rounded-full bg-yellow-500 text-black font-bold text-lg hover:bg-yellow-400 transition-colors flex items-center justify-center gap-2"
                    >
                        <QrCode size={20} />
                        Generate QR Code
                    </button>
                </div>
            )}

            {paymentStatus === "waiting" && (
                <div className="space-y-6">
                    {/* QR Code */}
                    <div className="text-center">
                        <div className="inline-block p-6 bg-white rounded-2xl shadow-xl">
                            <img
                                src={qrCodeUrl}
                                alt="Binance Pay QR Code"
                                className="w-64 h-64"
                            />
                        </div>
                        <p className="text-sm text-muted-foreground mt-4">
                            Scan with Binance app to complete payment
                        </p>
                    </div>

                    {/* Mobile Auto-Open */}
                    <a
                        href={`binance://pay/${orderId}`}
                        className="block w-full px-6 py-3 rounded-full bg-yellow-500 text-black font-semibold hover:bg-yellow-400 transition-colors flex items-center justify-center gap-2"
                    >
                        <Smartphone size={20} />
                        Open in Binance App
                    </a>

                    {/* Waiting Status */}
                    <div className="p-6 bg-secondary/30 rounded-xl text-center">
                        <Loader2 className="animate-spin mx-auto mb-3 text-yellow-500" size={32} />
                        <div className="font-semibold text-foreground mb-1">Waiting for payment...</div>
                        <div className="text-sm text-muted-foreground">
                            Simulating payment confirmation in {countdown}s
                        </div>
                    </div>

                    {/* Order Info */}
                    <div className="p-4 bg-secondary/30 rounded-xl">
                        <div className="text-xs text-muted-foreground mb-2">Order Details</div>
                        <div className="space-y-1 text-sm">
                            <div className="flex justify-between">
                                <span className="text-muted-foreground">Order ID:</span>
                                <span className="font-mono text-foreground">{orderId}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-muted-foreground">Product:</span>
                                <span className="text-foreground truncate max-w-[200px]">{productInfo.title}</span>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
